[package]
name = "day-3"
version = "0.1.0"
authors = ["rust7 <rust.91@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
